# Generated by Django 2.2.6 on 2020-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200203_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='company/covers'),
        ),
    ]
