# Generated by Django 2.2.6 on 2020-02-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessor',
            name='phoneno',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
