# Generated by Django 2.2.6 on 2020-02-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('discounted_from', models.IntegerField(blank=True, null=True)),
                ('availability', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(upload_to='product/images')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
