# Generated by Django 2.2.6 on 2020-02-14 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('per', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('additional_features', models.CharField(help_text='seperate each by Comma (,)', max_length=100)),
                ('image', models.ImageField(upload_to='properties/image')),
                ('quantity_available', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessor.Lessor')),
            ],
        ),
    ]
