# Generated by Django 2.2.6 on 2020-02-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images'),
        ),
        migrations.AddField(
            model_name='property',
            name='videos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
