# Generated by Django 2.2.6 on 2020-02-21 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profession', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='skill/image')),
                ('cover', models.ImageField(upload_to='skill/cover')),
                ('language', models.CharField(max_length=250)),
                ('min_wage', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, help_text='Type comma twice (,,) to add paragraph', null=True)),
                ('school', models.CharField(blank=True, max_length=250, null=True)),
                ('start_end_date', models.CharField(blank=True, max_length=250, null=True)),
                ('school_qualification', models.CharField(blank=True, max_length=250, null=True)),
                ('employer', models.CharField(blank=True, max_length=250, null=True)),
                ('job_start_end_date', models.CharField(blank=True, max_length=250, null=True)),
                ('job_description', models.CharField(blank=True, max_length=250, null=True)),
                ('job_image', models.ImageField(upload_to='skill/cover')),
                ('job_url', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('linkdin', models.CharField(blank=True, max_length=250, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('ongoing_jobs', models.ManyToManyField(related_name='is_completed', to='jobs.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
