# Generated by Django 2.2.6 on 2020-02-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='ongoing_jobs',
            field=models.ManyToManyField(blank=True, to='jobs.Job'),
        ),
    ]
