# Generated by Django 2.2.6 on 2020-02-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0005_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='top_ten',
            field=models.BooleanField(default=False),
        ),
    ]
