# Generated by Django 2.2.6 on 2020-02-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0007_auto_20200227_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='skills',
            field=models.TextField(blank=True, help_text='seperate each with comma (,)', null=True),
        ),
    ]
