# Generated by Django 2.2.6 on 2020-02-21 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Type comma twice (,,) to add paragraph')),
                ('category', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('job_type', models.CharField(blank=True, max_length=200, null=True)),
                ('wages', models.CharField(blank=True, max_length=200, null=True)),
                ('job_time', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Employer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
