# Generated by Django 2.2.6 on 2020-02-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200222_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_wage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_wage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
